import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  dir: 'rtl' | 'ltr';
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Navigation & Layout
    'home': 'الرئيسية',
    'my_orders': 'طلباتي',
    'orders': 'طلباتي',
    'active_orders': 'الطلبات الحالية',
    'past_orders': 'الطلبات السابقة',
    'favorites': 'المفضلة',
    'my_favorites': 'قائمتي المفضلة',
    'cart': 'السلة',
    'my_cart': 'سلة المشتريات',
    'account': 'حسابي',
    'my_account': 'حسابي',
    'profile': 'الملف الشخصي',
    'settings': 'الإعدادات',
    'privacy_policy': 'سياسة الخصوصية',
    'contact_us': 'تواصل معنا',
    'support': 'الدعم والمساعدة',
    'whatsapp': 'واتساب',
    'direct_call': 'اتصال مباشر',
    'share': 'مشاركة',
    'menu': 'القائمة',
    'preferences': 'التفضيلات',
    'language': 'اللغة',
    'language_country': 'اللغة والبلد',
    'sign_in': 'تسجيل الدخول',
    'sign_out': 'تسجيل الخروج',
    'logout': 'تسجيل الخروج',
    'welcome': 'مرحباً بك',
    'guest_sign_in_hint': 'سجل دخولك للاستفادة من الميزات',
    'app_tagline': 'خدمة التوصيل الأسرع في المملكة',
    'support_title': 'نحن معك..',
    'support_subtitle': 'اختر وسيلة التواصل المناسبة لك',
    'talk_directly': 'تحدث مباشرة',
    'instant_call': 'مكالمة فورية',
    'quick_links': 'روابط سريعة',
    'all_rights_reserved': 'جميع الحقوق محفوظة',
    'app_open_now': 'التطبيق مفتوح الآن',
    'app_closed_now': 'التطبيق مغلق حالياً',
    'working_hours': 'ساعات العمل',
    'open': 'مفتوح',
    'closed': 'مغلق',

    // Search & Categories
    'search_placeholder': 'ابحث عن مطعم أو وجبة...',
    'search_restaurants_meals': 'ابحث عن مطعم، كافيه، أو وجبة مفضلة...',
    'search_results': 'نتائج البحث',
    'no_results_found': 'لم يتم العثور على نتائج',
    'try_different_search': 'جرب البحث بكلمات أخرى أو تصفح الأقسام',
    'categories': 'التصنيفات',
    'browse_categories': 'تصفح حسب التصنيف',
    'all_categories': 'جميع الأصناف',
    'all': 'الكل',
    'special_offers': 'عروض وتخفيضات حصرية',
    'featured_restaurants': 'المطاعم والمتاجر المميزة',
    'delivery_time': 'دقيقة',
    'delivery_fee': 'رسوم التوصيل',
    'free_delivery': 'توصيل مجاني',
    'min_order': 'الحد الأدنى',
    'rating': 'التقييم',
    'reviews': 'تقييم',

    // Store & Food Details
    'menu_sections': 'قائمة الوجبات',
    'add_to_cart': 'إضافة للسلة',
    'added_to_cart': 'تمت الإضافة للسلة',
    'customize_order': 'تخصيص الطلب',
    'required': 'إجباري',
    'optional': 'اختياري',
    'choose_options': 'اختر الإضافات والخيارات',
    'special_instructions': 'ملاحظات خاصة للطلب',
    'special_instructions_placeholder': 'مثال: بدون بصل، زيادة شطة...',
    'quantity': 'الكمية',
    'price': 'السعر',
    'currency': 'ريال',
    'available': 'متوفر',
    'out_of_stock': 'غير متوفر حالياً',
    'busy_now': 'المطعم مشغول حالياً',
    'closed_now': 'المطعم مغلق حالياً',

    // Cart & Checkout
    'empty_cart_title': 'سلة المشتريات فارغة',
    'empty_cart_desc': 'لم تقم بإضافة أي وجبات أو منتجات بعد. تصفح أفضل المطاعم وابدأ طلبك الآن!',
    'start_shopping': 'ابدأ التسوق وتصفح المطاعم',
    'order_summary': 'ملخص الطلب',
    'subtotal': 'المجموع الفرعي',
    'discount': 'الخصم',
    'tax': 'الضريبة',
    'total': 'المجموع الإجمالي',
    'delivery_info': 'بيانات التوصيل',
    'delivery_address': 'عنوان التوصيل',
    'change_address': 'تغيير العنوان',
    'add_address': 'إضافة عنوان جديد',
    'select_saved_address': 'اختر من العناوين المحفوظة',
    'recipient_name': 'اسم المستلم',
    'phone_number': 'رقم الهاتف / الجوال',
    'order_notes': 'ملاحظات إضافية للتوصيل',
    'payment_method': 'طريقة الدفع',
    'cash_on_delivery': 'الدفع نقداً عند الاستلام',
    'wallet_payment': 'الدفع من المحفظة الإلكترونية',
    'card_payment': 'بطاقة بنكية / دفع إلكتروني',
    'have_coupon': 'هل لديك كود خصم؟',
    'apply_coupon': 'تطبيق الكود',
    'coupon_applied': 'تم تطبيق كود الخصم بنجاح',
    'confirm_and_order': 'تأكيد وإرسال الطلب',
    'sending_order': 'جاري إرسال الطلب...',
    'order_placed_success': 'تم إرسال طلبك بنجاح!',
    'scheduled_order': 'طلب مجدول',
    'schedule_delivery': 'جدولة موعد التوصيل',

    // Order Tracking & Statuses
    'order_tracking': 'تتبع الطلب',
    'order_number': 'طلب رقم',
    'live_tracking_active': 'التحديث المباشر مفعل لحظة بلحظة',
    'estimated_arrival': 'الوقت المتوقع للوصول',
    'order_progress': 'مرحلة التقدم',
    'driver_info': 'بيانات سائق التوصيل',
    'waiting_driver_location': 'في انتظار إشارة موقع السائق...',
    'call_driver': 'اتصال بالسائق',
    'chat_driver': 'مراسلة السائق',
    'cancel_order': 'إلغاء الطلب',
    'confirm_cancel': 'تأكيد الإلغاء',
    'cancel_reason_prompt': 'لماذا تريد إلغاء الطلب؟',
    'rate_order': 'تقييم الطلب والخدمة',
    'order_timeline': 'سجل ومراحل الطلب',
    'status_pending': 'قيد المراجعة',
    'status_confirmed': 'تم التأكيد',
    'status_preparing': 'جاري التحضير',
    'status_ready': 'جاهز للاستلام',
    'status_picked_up': 'تم الاستلام',
    'status_on_way': 'في الطريق إليك',
    'status_delivered': 'تم التسليم بنجاح',
    'status_cancelled': 'ملغي',
    'status_scheduled': 'مجدول',

    // Profile & Addresses
    'edit_profile': 'تعديل الملف الشخصي',
    'full_name': 'الاسم الكامل',
    'email_address': 'البريد الإلكتروني',
    'save_changes': 'حفظ التغييرات',
    'my_saved_addresses': 'عناويني المحفوظة',
    'saved_addresses_desc': 'إدارة وتعديل عناوين التوصيل الخاصة بك',
    'default_address': 'العنوان الافتراضي',
    'set_as_default': 'تعيين كافتراضي',
    'delete_address': 'حذف العنوان',
    'address_title': 'اسم العنوان (المنزل، العمل...)',
    'city': 'المدينة',
    'street': 'الشارع / الحي',
    'building': 'رقم المبنى / الشقة',
    'auto_locate': 'تحديد موقعي عبر GPS',
    'wallet_balance': 'رصيد المحفظة',
    'total_spent': 'إجمالي المشتريات',
    'completed_orders': 'طلبات مكتملة',

    // General Actions & Feedback
    'confirm': 'تأكيد',
    'cancel': 'إلغاء',
    'back': 'رجوع',
    'save': 'حفظ',
    'delete': 'حذف',
    'edit': 'تعديل',
    'retry': 'إعادة المحاولة',
    'loading': 'جاري التحميل...',
    'success': 'تم بنجاح',
    'error': 'حدث خطأ',
    'copied': 'تم النسخ',
    'copied_desc': 'تم نسخ الرابط بنجاح',
    'login_required': 'يجب تسجيل الدخول أولاً',
    'logout_confirm_title': 'تأكيد تسجيل الخروج',
    'logout_confirm_desc': 'عند تسجيل الخروج سوف يتم مسح جلسة الدخول الحالية. هل أنت متأكد؟',
    'clear_cart': 'مسح السلة',
    'customer_info': 'معلومات العميل',
    'name_placeholder': 'الاسم *',
    'phone_placeholder': 'رقم الهاتف *',
    'email_placeholder': 'البريد الإلكتروني (اختياري)',
    'delivery_address_header': 'عنوان التوصيل',
    'pick_location_map': 'اختر موقع التوصيل من الخريطة',
    'or_manual_address': 'أو أدخل العنوان يدوياً:',
    'manual_address_placeholder': 'أدخل عنوان التوصيل بالتفصيل *',
    'location_accurate': 'تم تحديد الموقع بدقة',
    'coordinates': 'الإحداثيات',
    'accurate_delivery_msg': 'سيتم توصيل طلبك بدقة للموقع المحدد',
    'order_notes_title': 'ملاحظات الطلب',
    'order_notes_placeholder': 'أضف ملاحظات للطلب (اختياري)',
    'payment_method_title': 'طريقة الدفع',
    'cash_on_del': 'نقداً عند الاستلام',
    'e_wallet': 'المحفظة الإلكترونية',
    'e_payment': 'دفع إلكتروني',
    'subtotal_label': 'المجموع الفرعي',
    'delivery_label': 'التوصيل',
    'total_label': 'الإجمالي',
    'delivery_fee_hint': 'يرجى تحديد عنوان التوصيل لاحتساب سعر التوصيل بدقة',
    'app_closed_cart': 'التطبيق مغلق حالياً',
    'store_closed_cart': 'المتجر مغلق حالياً',
    'work_hours': 'أوقات العمل',
    'confirming_order': 'جاري تأكيد الطلب...',
    'outside_zone_button': '⚠️ الموقع خارج نطاق التوصيل',
    'select_location_to_continue': 'يرجى تحديد الموقع للمتابعة',
    'confirm_order_btn': 'تأكيد الطلب',
    'outside_zone_warning': 'لا يمكن إرسال الطلب لأن موقع التوصيل يقع خارج المناطق المعتمدة.',
    'empty_cart_message': 'أضف بعض الوجبات اللذيذة لبدء طلبك',
    'browse_food': 'تصفح المأكولات',
    'no_internet_warning': 'لا يوجد اتصال بالإنترنت - يرجى التحقق من الاتصال',
    'confirm_order_title': 'تأكيد الطلب',
    'confirm_order_prompt': 'هل أنت متأكد من رغبتك في إرسال هذا الطلب بإجمالي',
    'confirm_and_send': 'تأكيد وإرسال',
    'location_outside_zone_title': 'الموقع المحدد خارج نطاق التوصيل',
    'change_location_now': 'تغيير الموقع الآن',
    'view_details': 'عرض التفاصيل',
    'order_placed_toast': 'تم تأكيد طلبك بنجاح!',
    'contact_soon': 'سيتم التواصل معك قريباً',
    'missing_info': 'معلومات ناقصة',
    'fill_required': 'يرجى ملء جميع الحقول المطلوبة',
    'cart_is_empty': 'السلة فارغة',
    'add_items_first': 'أضف بعض العناصر قبل تأكيد الطلب',
    'restaurant_not_found': 'المطعم غير موجود',
    'back_to_home': 'العودة للرئيسية',
    'rate_restaurant_title': 'قيّم المطعم',
    'rate_store_name': 'قيّم {name}',
    'rate_warning_star': 'اختر عدد النجوم أولاً',
    'rate_success_title': 'شكراً لتقييمك!',
    'rate_success_desc': 'تم إرسال تقييمك بنجاح.',
    'rate_error_desc': 'تعذّر إرسال التقييم، حاول مجدداً.',
    'how_was_experience': 'كيف كانت تجربتك مع هذا المطعم؟',
    'rate_send': 'إرسال التقييم',
    'sending_rate': 'جاري الإرسال...',
    'comment_placeholder': 'أضف تعليقاً (اختياري)...',
    'rate_terrible': 'سيئ جداً',
    'rate_bad': 'سيئ',
    'rate_ok': 'مقبول',
    'rate_good': 'جيد',
    'rate_excellent': 'ممتاز',
    'prices_match_store': 'الأسعار مطابقة للمطعم',
    'order_takes': 'الطلب يستغرق',
    'minutes_unit': 'دقيقة',
    'offers_tag': 'عروض',
    'special_offers_sec': 'عروض خاصة',
    'no_items_in_section': 'لا توجد عناصر في هذا القسم',
    'no_items_added_yet': 'لم يتم إضافة أصناف بعد',
    'currency_symbol': 'ر.ي',
    'added_to_fav': 'تمت الإضافة للمفضلة',
    'removed_from_fav': 'تمت الإزالة من المفضلة',
    'fav_added_msg': 'تم إضافة {name} إلى قائمة مفضلاتك',
    'fav_removed_msg': 'تمت إزالة {name} من قائمة مفضلاتك',
    'meal_default_name': 'الوجبة',
    'closed_status': 'مغلق',
    'open_status': 'مفتوح',
    'discount_label': 'خصم',
    'bundle_offer_tag': 'عرض خاص',
    'unavailable': 'غير متوفر',
  },
  en: {
    // Navigation & Layout
    'home': 'Home',
    'my_orders': 'My Orders',
    'orders': 'My Orders',
    'active_orders': 'Active Orders',
    'past_orders': 'Past Orders',
    'favorites': 'Favorites',
    'my_favorites': 'My Favorites',
    'cart': 'Cart',
    'my_cart': 'Shopping Cart',
    'account': 'My Account',
    'my_account': 'My Account',
    'profile': 'Profile',
    'settings': 'Settings',
    'privacy_policy': 'Privacy Policy',
    'contact_us': 'Contact Us',
    'support': 'Help & Support',
    'whatsapp': 'WhatsApp',
    'direct_call': 'Direct Call',
    'share': 'Share',
    'menu': 'Menu',
    'preferences': 'Preferences',
    'language': 'Language',
    'language_country': 'Language & Country',
    'sign_in': 'Sign In',
    'sign_out': 'Sign Out',
    'logout': 'Log Out',
    'welcome': 'Welcome',
    'guest_sign_in_hint': 'Sign in to enjoy full benefits',
    'app_tagline': 'Fastest delivery service in the region',
    'support_title': 'We are here for you..',
    'support_subtitle': 'Choose your preferred communication method',
    'talk_directly': 'Chat directly',
    'instant_call': 'Instant call',
    'quick_links': 'Quick Links',
    'all_rights_reserved': 'All rights reserved',
    'app_open_now': 'Service is open now',
    'app_closed_now': 'Service is currently closed',
    'working_hours': 'Working Hours',
    'open': 'Open',
    'closed': 'Closed',

    // Search & Categories
    'search_placeholder': 'Search for restaurant or dish...',
    'search_restaurants_meals': 'Search for restaurant, cafe, or meal...',
    'search_results': 'Search Results',
    'no_results_found': 'No results found',
    'try_different_search': 'Try searching with different keywords or browse categories',
    'categories': 'Categories',
    'browse_categories': 'Browse by Category',
    'all_categories': 'All Categories',
    'all': 'All',
    'special_offers': 'Exclusive Offers & Deals',
    'featured_restaurants': 'Featured Restaurants & Stores',
    'delivery_time': 'min',
    'delivery_fee': 'Delivery Fee',
    'free_delivery': 'Free Delivery',
    'min_order': 'Min Order',
    'rating': 'Rating',
    'reviews': 'reviews',

    // Store & Food Details
    'menu_sections': 'Food Menu',
    'add_to_cart': 'Add to Cart',
    'added_to_cart': 'Added to cart',
    'customize_order': 'Customize Order',
    'required': 'Required',
    'optional': 'Optional',
    'choose_options': 'Choose additions and options',
    'special_instructions': 'Special instructions for order',
    'special_instructions_placeholder': 'e.g., no onions, extra spicy...',
    'quantity': 'Quantity',
    'price': 'Price',
    'currency': 'YER',
    'available': 'Available',
    'out_of_stock': 'Currently Out of Stock',
    'busy_now': 'Store is currently busy',
    'closed_now': 'Store is currently closed',

    // Cart & Checkout
    'empty_cart_title': 'Your cart is empty',
    'empty_cart_desc': 'You have not added any items yet. Explore top restaurants and start ordering now!',
    'start_shopping': 'Start shopping and explore stores',
    'order_summary': 'Order Summary',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'tax': 'Tax',
    'total': 'Grand Total',
    'delivery_info': 'Delivery Details',
    'delivery_address': 'Delivery Address',
    'change_address': 'Change Address',
    'add_address': 'Add New Address',
    'select_saved_address': 'Select from saved addresses',
    'recipient_name': 'Recipient Name',
    'phone_number': 'Phone / Mobile Number',
    'order_notes': 'Additional delivery notes',
    'payment_method': 'Payment Method',
    'cash_on_delivery': 'Cash on Delivery',
    'wallet_payment': 'Pay with Wallet',
    'card_payment': 'Bank Card / Online Payment',
    'have_coupon': 'Have a discount coupon?',
    'apply_coupon': 'Apply Coupon',
    'coupon_applied': 'Coupon applied successfully',
    'confirm_and_order': 'Confirm & Place Order',
    'sending_order': 'Sending order...',
    'order_placed_success': 'Your order has been placed successfully!',
    'scheduled_order': 'Scheduled Order',
    'schedule_delivery': 'Schedule Delivery Time',

    // Order Tracking & Statuses
    'order_tracking': 'Order Tracking',
    'order_number': 'Order #',
    'live_tracking_active': 'Live tracking is active in real-time',
    'estimated_arrival': 'Estimated Arrival Time',
    'order_progress': 'Progress Status',
    'driver_info': 'Delivery Driver Info',
    'waiting_driver_location': 'Waiting for driver GPS signal...',
    'call_driver': 'Call Driver',
    'chat_driver': 'Chat Driver',
    'cancel_order': 'Cancel Order',
    'confirm_cancel': 'Confirm Cancellation',
    'cancel_reason_prompt': 'Why do you want to cancel the order?',
    'rate_order': 'Rate Order & Service',
    'order_timeline': 'Order History & Timeline',
    'status_pending': 'Pending Review',
    'status_confirmed': 'Confirmed',
    'status_preparing': 'Preparing',
    'status_ready': 'Ready for Pickup',
    'status_picked_up': 'Picked Up',
    'status_on_way': 'On the Way',
    'status_delivered': 'Delivered Successfully',
    'status_cancelled': 'Cancelled',
    'status_scheduled': 'Scheduled',

    // Profile & Addresses
    'edit_profile': 'Edit Profile',
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'save_changes': 'Save Changes',
    'my_saved_addresses': 'Saved Addresses',
    'saved_addresses_desc': 'Manage your delivery addresses',
    'default_address': 'Default Address',
    'set_as_default': 'Set as Default',
    'delete_address': 'Delete Address',
    'address_title': 'Address Title (Home, Work...)',
    'city': 'City',
    'street': 'Street / Area',
    'building': 'Building / Apt #',
    'auto_locate': 'Locate via GPS',
    'wallet_balance': 'Wallet Balance',
    'total_spent': 'Total Spent',
    'completed_orders': 'Completed Orders',

    // General Actions & Feedback
    'confirm': 'Confirm',
    'cancel': 'Cancel',
    'back': 'Back',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'retry': 'Retry',
    'loading': 'Loading...',
    'success': 'Success',
    'error': 'Error occurred',
    'copied': 'Copied',
    'copied_desc': 'Store link copied successfully',
    'login_required': 'Login is required',
    'logout_confirm_title': 'Confirm Sign Out',
    'logout_confirm_desc': 'Signing out will clear your active session. Are you sure you want to sign out?',
    'clear_cart': 'Clear Cart',
    'customer_info': 'Customer Information',
    'name_placeholder': 'Full Name *',
    'phone_placeholder': 'Phone Number *',
    'email_placeholder': 'Email Address (optional)',
    'delivery_address_header': 'Delivery Address',
    'pick_location_map': 'Select delivery location on map',
    'or_manual_address': 'Or enter address manually:',
    'manual_address_placeholder': 'Enter detailed delivery address *',
    'location_accurate': 'Location pinned accurately',
    'coordinates': 'Coordinates',
    'accurate_delivery_msg': 'Your order will be delivered accurately to the pinned location',
    'order_notes_title': 'Order Notes',
    'order_notes_placeholder': 'Add notes for the order (optional)',
    'payment_method_title': 'Payment Method',
    'cash_on_del': 'Cash on Delivery',
    'e_wallet': 'Digital Wallet',
    'e_payment': 'Online Payment',
    'subtotal_label': 'Subtotal',
    'delivery_label': 'Delivery',
    'total_label': 'Total',
    'delivery_fee_hint': 'Please select your delivery address to calculate accurate delivery fee',
    'app_closed_cart': 'Application is currently closed',
    'store_closed_cart': 'Store is currently closed',
    'work_hours': 'Operating hours',
    'confirming_order': 'Confirming order...',
    'outside_zone_button': '⚠️ Location outside delivery zone',
    'select_location_to_continue': 'Please pin your location to continue',
    'confirm_order_btn': 'Confirm Order',
    'outside_zone_warning': 'Order cannot be placed because the location is outside supported delivery zones.',
    'empty_cart_message': 'Add delicious meals to start your order',
    'browse_food': 'Browse Foods & Stores',
    'no_internet_warning': 'No internet connection - please check your network',
    'confirm_order_title': 'Confirm Order',
    'confirm_order_prompt': 'Are you sure you want to place this order with total',
    'confirm_and_send': 'Confirm & Send',
    'location_outside_zone_title': 'Selected location is outside delivery zone',
    'change_location_now': 'Change Location Now',
    'view_details': 'View Details',
    'order_placed_toast': 'Your order has been confirmed successfully!',
    'contact_soon': 'We will reach out to you shortly',
    'missing_info': 'Missing Information',
    'fill_required': 'Please fill all required fields',
    'cart_is_empty': 'Cart is empty',
    'add_items_first': 'Add items before confirming order',
    'restaurant_not_found': 'Restaurant not found',
    'back_to_home': 'Back to Home',
    'rate_restaurant_title': 'Rate Restaurant',
    'rate_store_name': 'Rate {name}',
    'rate_warning_star': 'Please select a star rating first',
    'rate_success_title': 'Thank you for your rating!',
    'rate_success_desc': 'Your rating has been submitted successfully.',
    'rate_error_desc': 'Failed to submit rating, please try again.',
    'how_was_experience': 'How was your experience with this store?',
    'rate_send': 'Submit Rating',
    'sending_rate': 'Submitting...',
    'comment_placeholder': 'Add a comment (optional)...',
    'rate_terrible': 'Very Poor',
    'rate_bad': 'Poor',
    'rate_ok': 'Average',
    'rate_good': 'Good',
    'rate_excellent': 'Excellent',
    'prices_match_store': 'Prices match restaurant menu',
    'order_takes': 'Delivery takes approx',
    'minutes_unit': 'min',
    'offers_tag': 'Offers',
    'special_offers_sec': 'Special Offers',
    'no_items_in_section': 'No items found in this section',
    'no_items_added_yet': 'No dishes have been added yet',
    'currency_symbol': 'YER',
    'added_to_fav': 'Added to favorites',
    'removed_from_fav': 'Removed from favorites',
    'fav_added_msg': '{name} has been added to your favorites',
    'fav_removed_msg': '{name} has been removed from your favorites',
    'meal_default_name': 'Item',
    'closed_status': 'Closed',
    'open_status': 'Open',
    'discount_label': 'Discount',
    'bundle_offer_tag': 'Special Offer',
    'unavailable': 'Unavailable',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLangState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    const direction = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = direction;
    document.documentElement.lang = language;
    if (direction === 'ltr') {
      document.body.classList.add('direction-ltr');
      document.body.classList.remove('direction-rtl');
    } else {
      document.body.classList.add('direction-rtl');
      document.body.classList.remove('direction-ltr');
    }
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    const langDict = translations[language] || translations.ar;
    if (langDict[key]) {
      return langDict[key];
    }
    // Fallback to Arabic dict or provided fallback or key
    return translations.ar[key] || fallback || key;
  };

  const dir: 'rtl' | 'ltr' = language === 'ar' ? 'rtl' : 'ltr';
  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

